### ISSUE TITLE
Modem compatibility check

### ISSUE THREAD

**Issue by bam80** [stich86/lpac-libmbim-wrapper#1]
Hi, thanks for the project!

I have Quectel EP06-E modem and it doesn't seem to have AT commands required for the APDU backend.
I'm trying to guess it's firmware readiness for working LPA with external e-SIM.

The modem doesn't have an internal e-SIM and I don't have the external one either,
so I wonder if I could still run this `mbimcli` command to get some evidence of it's e-SIM support:
https://github.com/stich86/lpac-libmbim-wrapper/blob/4641f27e43478c79d37ab18e485bf75a9b5f7ffd/wrapper.py#L44

What do you think?

**Comment by stich86** [comment]
Logical channels are only available on eUICC (eSIM), so to test it, you need at least an eSIM physical card (like the Lenovo one that is very cheap).

As I've written in my git, this card is correctly recognized as eSIM on both Fox T99W175 (using physical SIM slot) and on Quectel RN502Q-GL (that doesn't have embedded eSIM but has AT commands)

I don't have other MBIM devices, so I cannot test it :)

**Comment by bam80** [comment]
> Logical channels are only fore eUICC (eSIM), so to test this wrapper you need at least an eSIM physical card

Right, but if the firmware doesn't have eSIM support, maybe it won't even recognize that `open-channel` command and the error return code will be different?

**Comment by stich86** [comment]
> > Logical channels are only fore eUICC (eSIM), so to test this wrapper you need at least an eSIM physical card
> 
> 
> 
> Right, but if the firmware doesn't have eSIM support, maybe it won't even recognize that `open-channel` command and the error return code will be different?

That commands should be executed at low level over MBIM, but as I've said it should be tested.

I've a friend with EP-06, I'm asking him if he can give it to me for a while, so I can test the eSIM on it using MBIM.

I let you know if I can succeed on this test ;)

**Comment by bam80** [comment]
Many thanks, that would be awesome! :) :handshake:

**Comment by bam80** [comment]
> I've a friend with EP-06, I'm asking him if he can give it to me for a while, so I can test the eSIM on it using MBIM.

If you have a chance to do that, please also check the fw revision with `ATI` command. Thanks!

**Comment by asbtlt** [comment]
I tested the T77W968 DW5821e, unfortunately it doesn't have the required AT commands (

**Comment by stich86** [comment]
> I tested the T77W968 DW5821e, unfortunately it doesn't have the required AT commands (

all Foxconn modules don't have AT commands, you need to use MBIM to interact with eSIM :)

**Comment by asbtlt** [comment]
> > I tested the T77W968 DW5821e, unfortunately it doesn't have the required AT commands (
> 
> all Foxconn modules don't have AT commands, you need to use MBIM to interact with eSIM :)

Thank you so much for the tip, indeed everything worked as it should!

**Comment by stich86** [comment]
Can you confirm that is working with t77? Let me know I can add to the tested list devices

Thx :)

**Comment by asbtlt** [comment]
> Can you confirm that is working with t77? Let me know I can add to the tested list devices
>
>Thx :)

Confirm profiles shows, now I will test downloading of new profiles. Otherwise I didn't notice any errors. My device is defined as /dev/cdc-wdm0

**Comment by stich86** [comment]
Good

Pls send me full model numeber (if it's the eSIM version) and firmware

Thanks :)

**Comment by asbtlt** [comment]
> Good
> 
> Pls send me full model numeber (if it's the eSIM version) and firmware
> 
> Thanks :)

ATI
Manufacturer: DELL
Model: 4116
Revision: T77W968.F1.0.0.5.2.GC.013  1  [May 31 2021 08:00:00]
SVN: 03
IMEI: 015833000854***
+GCAP: +CGSM
MPN: 01

**Comment by asbtlt** [comment]
May I ask? How many profiles can be loaded into the modem? Where to look for this information?

**Comment by stich86** [comment]
i think you have 8 slot on embedded eSIM

**Comment by asbtlt** [comment]
> i think you have 8 slot on embedded eSIM

Thx!

**Comment by asbtlt** [comment]
Good news in my variant

>manufacturer: Dell Inc.
>model: DW5821e Snapdragon X20 LTE
>firmware revision: T77W968.F1.0.0.5.2.GC.013 050
> in MBIM

I was able to download the profile via 
`./wrapper.py profile download -s rsp.truphone.com -m "QR-G-5C-1LS-1W1Z9P7"`

And this option didn't work, I don't know the reason, it gives 255 error.
`./wrapper.py profile download -a 'LPA:1$rsp.truphone.com$QR-G-5C-1LS-1W1Z9P7'`

**Comment by asbtlt** [comment]
> i think you have 8 slot on embedded eSIM

I've already downloaded 12 pieces, I'll keep checking capacity tomorrow )

**Comment by asbtlt** [comment]
Apparently my modem has 17 profiles, when trying to load one more profile, I get an authorization error with subject-code: 8.1, reason-code: 4.8.

**Comment by bam80** [comment]
> I've a friend with EP-06, I'm asking him if he can give it to me for a while, so I can test the eSIM on it using MBIM.
> 
> I let you know if I can succeed on this test ;)

Hi @stich86, any news so far?

**Comment by stich86** [comment]
I'm still waiting modules to arrive

**Comment by stich86** [comment]
Added Quectel EP-06, it works as expected over MBIM, same behaviour with AT commands like RM502.

I'm closing this issue for now, if someone wants to add new modems to the list, please open a PR

**Comment by bam80** [comment]
> Added Quectel EP-06, it works as expected over MBIM, same behaviour with AT commands like RM502.

Thanks, please share the firmware version (in parentheses around modem name in the [table](https://github.com/stich86/lpac-libmbim-wrapper?tab=readme-ov-file#test-done)  ) - I reached Quectel support and judging from their response it should be sensitive.

**Comment by stich86** [comment]
> > Added Quectel EP-06, it works as expected over MBIM, same behaviour with AT commands like RM502.
> 
> Thanks, please share the firmware version (in parentheses around modem name in the [table](https://github.com/stich86/lpac-libmbim-wrapper?tab=readme-ov-file#test-done) ) - I reached Quectel support and judging from their response it should be sensitive.

added :)

**Comment by bam80** [comment]
Oh, thanks - it's getting really interesting now,
your fw version is EP06ELAR04A05M4G,
whereas I got following reply from Quectel:
> 1. EP06ELAR04A06M4G version does not support LPAAT function and cannot be used in other ways.
> 2. EP06E uses RMNET dialing instead of MBIM dialing, and cannot manage ESIM through MBIM.
> 3. Qualcomm 9x40 platform originally did not support ESIM LPA, the current use is Quectel ESIM LPA solution, need to integrate the relevant database can be, the old version is not supported.

So your experience seems deviate from their response.. The more valuable it is!

PS:
it's still an open question if EP06ELAR04A06M4G and newer are actually work as well as EP06ELAR04A05M4G you have..

**Comment by stich86** [comment]
i think they talking about their LPA integration for embedded eSIM device (never seen one..), what we are using here is a set of MBIM commands to interact with eSIM chip.
For instance MiFi router that expose MBIM interface can interface with eSIM (like the one that i've tested), fun facts, it recognized eSIM also on Windows machine :)

**Comment by bam80** [comment]
For the reference, here was my original question to them:

> I’m interested if external e-SIM can be used for EP06-E module, we need LPA (Local Profile Agent) functioning (eSIM profiles downloading, etc.).
I know some modules do not have AT commands required, but still can be used with e-SIM via MBIM or QMI protocols.
Could you clarify the situation for EP06-E module please?
