### ISSUE TITLE
lpac package: wrong fork link

### ISSUE THREAD

**Issue by bam80** [stich86/lpac-libmbim-wrapper#13]
https://github.com/stich86/lpac-libmbim-wrapper/blob/feb800999059a5308af2009c8b60e754a9a5f976/README.md?plain=1#L142
The [fork](https://github.com/stich86/lpac-libmbim-wrapper) link doesn't point to a fork.

Also, can `libcurl-gnutls4` be used instead?

**Comment by stich86** [comment]
It was working only with OpenSSL, had same problem (cipher suite incompatibilty with gnutls and mbedtls).
Anyway i've fixed the link on the README
