### ISSUE TITLE
Clarify Quectel EP06-E logical channel AT-commands support

### ISSUE THREAD

**Issue by bam80** [stich86/lpac-libmbim-wrapper#15]
According to the table, your EP06 has some support for logical channel AT-commands:
https://github.com/stich86/lpac-libmbim-wrapper/blob/ad72a782207e009ac777245897f29547e506c96c/README.md?plain=1#L92-L95
I tried it on my EP06ELAR04A03M4G FW, but neither of them does seem to work:
```
AT+CCHO?
ERROR

AT+CCHC?
ERROR

AT+CGLA?
ERROR
```
Could you clarify how did you test it?

**Comment by stich86** [comment]
Sorry I don't have anymore the module to test and check firmware version.
If you had problem, i remove the AT mode from the list ;)

**Comment by bam80** [comment]
Could we keep this issue open as it still needs clarifying?
Thanks.

**Comment by stich86** [comment]
As I've said this module is not anymore in my possession.

If you had one and AT was not working, we can assume that I've done wrong test (I had it just for few days) may be :)
