### ISSUE TITLE
Readme: wrong link to the lpac fork

### ISSUE THREAD

**Issue by bam80** [stich86/lpac-libmbim-wrapper#18]
https://github.com/stich86/lpac-libmbim-wrapper/blob/d467bd83c0f28843d7d191652e8f16e11d2b22e0/README.md?plain=1#L142
The link points to this repo and not to the `lpac` (or whatever) fork, appears to be wrong.

**Comment by bam80** [comment]
Also, could you elaborate (maybe in the Readme) on why MbedTLS doesn't suit?
Maybe create an issue upstream to not maintain the fork, then?
Thanks.

**Comment by stich86** [comment]
Problem was related to cipher suite used by remote server.
When I first tested lpac had problems with mbedtls. Switched to OpenSSL resolved the issue.

**Comment by stich86** [comment]
Fixed the link to my repo link

**Comment by bam80** [comment]
Nitpick: just place #\<issue number> in the commit message, and it will be close automatically.
Easier to track also)

**Comment by bam80** [comment]
> When I first tested lpac had problems with mbedtls.

@stich86 @robimarko Could you provide the error in the Readme?
Thanks.

**Comment by stich86** [comment]
Sorry don't have a time.
Build by yourself and run a simple profile add and check with a tcpdump the error
