### ISSUE TITLE
port to shell (ash)

### ISSUE THREAD

**Issue by bam80** [stich86/lpac-libmbim-wrapper#20]
https://github.com/stich86/lpac-libmbim-wrapper/blob/6f0d86274f3340c32f9af941e8cfe88eb13352e2/README.md?plain=1#L143
The dependency size requirement for running this script on OpenWrt is quite significant - I left with just few hundred kilobytes free after installing it on my system with 16 MiB flash, so I was lucky.

I wonder if we could port this script to shell, to minimize dependency as `ash` is part of the system.

**Comment by stich86** [comment]
Too much complex and missing tools to porting in ash. If you want try by yourself, currently I don't have too much time to working on it
