### ISSUE TITLE
why is the `-p` flag required?

### ISSUE THREAD

**Issue by AndySchroder** [stich86/lpac-libmbim-wrapper#4]
On https://github.com/stich86/lpac-libmbim-wrapper/blob/4641f27e43478c79d37ab18e485bf75a9b5f7ffd/wrapper.py#L23 we have a `-p` flag that is passed to `mbimcli`. What is this for? It's not working for me with that. Getting the following:

```
$ sudo mbimcli -p -d /dev/cdc-wdm0 --ms-set-uicc-open-channel="application-id=a0000005591010ffffffff8900000100"
error: operation failed: MBIM protocol error: NotOpened
$
```

However, if I remove `-p`, I get:

```
$ sudo mbimcli -d /dev/cdc-wdm0 --ms-set-uicc-open-channel="application-id=a0000005591010ffffffff8900000100"
Succesfully retrieved open channel info:
	  status: 144
	 channel: 3
	response: 6F:1F:84:10:A0:00:00:05:59:10:10:FF:FF:FF:FF:89:00:00:01:00:A5:04:9F:65:01:FF:E0:05:82:03:02:02:02
$
```

**Comment by stich86** [comment]
`-p` is for Proxy call, otherwise each time you got error of not open channel

**Comment by AndySchroder** [comment]
okay, but I'm getting an error with it that says NotOpened

**Comment by stich86** [comment]
> okay, but I'm getting an error with it that says NotOpened

Which modem and libmbim version? I've tested it under Ubuntu 23.10 and OpenWrt SNAPSHOT without any issue using proxy mode

**Comment by AndySchroder** [comment]
```
$ mbimcli -V
mbimcli 1.28.0
Copyright (C) 2013-2021 Aleksander Morgado
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

$

**Comment by AndySchroder** [comment]
```
$ cat /etc/issue
Ubuntu 22.04.4 LTS \n \l
```

**Comment by AndySchroder** [comment]
```
  Hardware |            manufacturer: Quectel
           |                   model: EM120R-GL

```

**Comment by AndySchroder** [comment]
```
$ uname -a
Linux rd 5.15.0-1053-raspi #56-Ubuntu SMP PREEMPT Mon Apr 15 18:50:10 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by AndySchroder** [comment]
I can use lpac in AT mode fine by the way. That is undesirable though because ModemManager locks the tty up and I have to stop the ModemManager service to use lpac every time, which also disconnects my internet connection. I'm hoping MBIM mode won't have that problem.

**Comment by AndySchroder** [comment]
Where is the application-id coming from? Is that something that lpac makes up?

**Comment by stich86** [comment]
Yes all application ids are generated by LPAC, wrapper just get it from stdin and pass to mbimcli in a correct way

**Comment by AndySchroder** [comment]
Is ModemManager supposed to be started or stopped when using this wrapper?

**Comment by stich86** [comment]
If it's using MBIM port, I think it's better to close it

**Comment by AndySchroder** [comment]
Okay, I'm getting a little farther. Here's the new outcome:

1. shut down
2. remove power
3. restore power and boot
4. stop ModemManager
5. run `wrapper.py chip info`
6. it yields the chip info output expected, but then it won't close the channel and I get

```
INFO: Close channel 01
close channel_id: 1
Error executing command: error: operation failed: Unknown status 0x87430003
```

after that, nothing works again without starting back with (1).

**Comment by stich86** [comment]
> Okay, I'm getting a little farther. Here's the new outcome:
> 
> 
> 
> 1. shut down
> 
> 2. remove power
> 
> 3. restore power and boot
> 
> 4. stop ModemManager
> 
> 5. run `wrapper.py chip info`
> 
> 6. it yields the chip info output expected, but then it won't close the channel and I get
> 
> 
> 
> ```
> 
> INFO: Close channel 01
> 
> close channel_id: 1
> 
> Error executing command: error: operation failed: Unknown status 0x87430003
> 
> ```
> 
> 
> 
> after that, nothing works again without starting back with (1).

What's happen if you remove -p form mbimcli?

**Comment by AndySchroder** [comment]
https://aleksander.es/data/20210421%20-%20Introduction%20to%20ModemManager.pdf page 22 talks about what the mbim-proxy proxy does. Apparently it allows you to keep ModemManager running if you use it.

**Comment by AndySchroder** [comment]
https://github.com/linux-mobile-broadband/libmbim/blob/214bacbc1ce72121dd89ba09e0598a6f05078f8e/NEWS#L306 might be related.

**Comment by AndySchroder** [comment]
Also related: https://github.com/linux-mobile-broadband/libmbim/blob/214bacbc1ce72121dd89ba09e0598a6f05078f8e/NEWS#L337 .

**Comment by AndySchroder** [comment]
> > Okay, I'm getting a little farther. Here's the new outcome:
> > 
> > 1. shut down
> > 2. remove power
> > 3. restore power and boot
> > 4. stop ModemManager
> > 5. run `wrapper.py chip info`
> > 6. it yields the chip info output expected, but then it won't close the channel and I get
> > 
> > ```
> > 
> > INFO: Close channel 01
> > 
> > close channel_id: 1
> > 
> > Error executing command: error: operation failed: Unknown status 0x87430003
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > after that, nothing works again without starting back with (1).
> 
> What's happen if you remove -p form mbimcli?

Seems like removing -p doesn't work if mbim-proxy is running, just times out. If you manually kill mbim-proxy, seems you can run without -p because the proxy isn't started. If you kill mbim-proxy and run with -p, it automatically restarts mbim-proxy. I am testing all this with `sudo mbimcli -d /dev/cdc-wdm1 --ms-query-uicc-application-list`, which doesn't seem to be having problems.

**Comment by AndySchroder** [comment]
See also, https://modemmanager.org/docs/modemmanager/debugging/#qmi-proxy-or-mbim-proxy-debug-logs .

**Comment by AndySchroder** [comment]
Now I'm getting:

```
$ sudo mbimcli -p -d /dev/cdc-wdm1 --ms-set-uicc-open-channel="application-id=a0000005591010ffffffff8900000101"
error: operation failed: Unknown status 0x87430001
$
```

This seems to be the same with and without mbim-proxy. Not sure why the error is different now.

**Comment by AndySchroder** [comment]
> Okay, I'm getting a little farther. Here's the new outcome:
> 
>     1. shut down
> 
>     2. remove power
> 
>     3. restore power and boot
> 
>     4. stop ModemManager
> 
>     5. run `wrapper.py chip info`
> 
>     6. it yields the chip info output expected, but then it won't close the channel and I get
> 
> 
> ```
> INFO: Close channel 01
> close channel_id: 1
> Error executing command: error: operation failed: Unknown status 0x87430003
> ```
> 
> after that, nothing works again without starting back with (1).

Correction, running `sudo mmcli -m 2 -r` will allow it to reset without requiring the power cycle. If I do that, I can run

```
sudo mbimcli -p -d /dev/cdc-wdm1 --ms-set-uicc-open-channel="application-id=a0000005591010ffffffff8900000100"
```
successfully (2) times before it errors out and requires `sudo mmcli -m 3 -r` to be run to reset it.

**Comment by AndySchroder** [comment]
Wondering what eSIM and modem you are using?

How does this command select which SIM it is working on with a dual SIM modem?

**Comment by AndySchroder** [comment]
Okay, I figured out the bug, your script wasn't closing the channel. Here is the fix.

```

@@ -76,8 +81,8 @@ def handle_type_apdu(func: str, param: str):
 
     if func == "logic_channel_close":
         try:
-            print(f"INFO: Close channel {param}")
-            close_channel(int(param))
+            print(f"INFO: Close channel {CHANNEL_ID}")
+            close_channel(int(CHANNEL_ID))
             return {"ecode": 0}
         except subprocess.CalledProcessError as e:
             print(e)


```


Possibly you are using another SIM or modem that allow more active channels and was more tolerant of this bug?

**Comment by AndySchroder** [comment]
Okay, so I'm able to use

```
sudo wrapper.py profile enable 89852350923580233317
```

followed by

```
sudo mmcli -m 2 -r
```

to change the profile on the eSIM and then re-load it.

Not sure if there is a better way to re-load the eSIM without resetting the entire modem? However, the point is, I don't need to stop ModemManager to do this. The mbim-proxy allows both to communicate with the modem at the same time.

**Comment by AndySchroder** [comment]
@z3ntu, I think lpac-libqmi-wrapper might have the same bug here https://github.com/z3ntu/lpac-libqmi-wrapper/blob/0ff0bb62273bba2a2d530f5eb7863dfda4105528/lpac-libqmi-wrapper.py#L96 .

**Comment by stich86** [comment]
> Wondering what eSIM and modem you are using?
> 
> 
> 
> How does this command select which SIM it is working on with a dual SIM modem?

I've tested with Foxconn T99W175 using embedded eSIM (on slot 2) and physical eSIM (Levovo Thales) on slot 1

And in a modem without eSIM (using physical one) on Quectel RM502GQ-GL

**Comment by AndySchroder** [comment]
fixed by https://github.com/stich86/lpac-libmbim-wrapper/pull/6

**Comment by bam80** [comment]
Could we reopen this?
The current code still requires `-p`, and the reason was just found:
https://github.com/stich86/lpac-libmbim-wrapper/issues/8#issuecomment-2166837603

So the real fix is yet pending.

**Comment by AndySchroder** [comment]
Not sure that these are related. I also don't understand the comment you link to.

I think my original issue with the `-p` flag might have been something jammed up with the mbim-proxy after lots of testing. After I understood what the proxy was for and restarted everything it exposed a new issue, which was then fixed by https://github.com/stich86/lpac-libmbim-wrapper/pull/6 .

**Comment by bam80** [comment]
The issue is, the `-p` flag is currently hardcoded and won't work if you don't use mbim-proxy and/or MM.
To make it work a such way, the linked fix is needed, then the flag could be made optional.

**Comment by bam80** [comment]
@AndySchroder does this make sense?
If you disagree to reopen this issue, I'll probably open a new one.
