### ISSUE TITLE
Feature request: port to lpac MBIM APDU backend

### ISSUE THREAD

**Issue by bam80** [stich86/lpac-libmbim-wrapper#7]
Just a placeholder for:
https://github.com/estkme-group/lpac/issues/94

**Comment by stich86** [comment]
looks like someone has started the implementation: https://github.com/estkme-group/lpac/pull/166

i'll close the issue, when it will be "standard", i'll put the repository in read-only mode. I think we don't need it anymore :)

**Comment by bam80** [comment]
Yeah, that's great. It would be awesome if you could test it yourself, though.
